class MockExamInstructions {
  static final Map<String, Map<bool, String>> instructions = {
    's': {
      true: '1. The group consists of Physics, Chemistry and Biology.\n2. The duration of the examination will be 120 minutes.\n3. You need to attempt all the 198 Multi-Choice Questions.\n4. The mock examination consists of 50 questions each from Physics and Chemistry, 98 questions from Biology.\n5. All the questions in level-1 mock examination will appear from simple category questions bank.\n6. You need to score 70% and more marks in each of the 50 consecutive examinations to qualify for the next level.\n7. In case, you want to leave the examination due to some unavoidable situation, the same examination will continue for the remaining time. You will not be able to attempt the next examination.\n8. All your attempted examinations will be saved in the Evaluation bucket to enable to monitor your average score.\n9. You will also be able to evaluate each and every attempted examination question by question in the Evaluation bucket.',
      false: '1. The group consists of Physics, Chemistry and Mathematics.\n2. The duration of the examination will be 120 minutes.\n3. You need to attempt all the 198 Multi-Choice Questions.\n4. The mock examination consists of 50 questions each from Physics and Chemistry, 98 questions from Mathematics.\n5. All the questions in level-1 mock examination will appear from simple category questions bank.\n6. You need to score 70% and more marks in each of the 50 consecutive examinations to qualify for the next level.\n7. In case, you want to leave the examination due to some unavoidable situation, the same examination will continue for the remaining time. You will not be able to attempt the next examination.\n8. All your attempted examinations will be saved in the Evaluation bucket to enable to monitor your average score.\n9. You will also be able to evaluate each and every attempted examination question by question in the Evaluation bucket.',
    },
    'm': {
      true: '1. The group consists of Physics, Chemistry and Biology.\n2. The duration of the examination will be 120 minutes.\n3. You need to attempt all the 198 Multi-Choice Questions.\n4. The mock examination consists of 50 questions each from Physics and Chemistry, 98 questions from Biology.\n5. All the questions in level-2 mock examination will appear 40% from simple and 60% from medium category questions bank.\n6. You need to score 70% and more marks in each of the 50 consecutive examinations to qualify for the next level.\n7. In case, you want to leave the examination due to some unavoidable situation, the same examination will continue for the remaining time. You will not be able to attempt the next examination.\n8. All your attempted examinations will be saved in the Evaluation bucket to enable to monitor your average score.\n9. You will also be able to evaluate each and every attempted examination question by question in the Evaluation bucket.',
      false: '1. The group consists of Physics, Chemistry and Mathematics.\n2. The duration of the examination will be 120 minutes.\n3. You need to attempt all the 198 Multi-Choice Questions.\n4. The mock examination consists of 50 questions each from Physics and Chemistry, 98 questions from Mathematics.\n5. All the questions in level-2 mock examination will appear 40% from simple and 60% from medium category questions bank.\n6. You need to score 70% and more marks in each of the 50 consecutive examinations to qualify for the next level.\n7. In case, you want to leave the examination due to some unavoidable situation, the same examination will continue for the remaining time. You will not be able to attempt the next examination.\n8. All your attempted examinations will be saved in the Evaluation bucket to enable to monitor your average score.\n9. You will also be able to evaluate each and every attempted examination question by question in the Evaluation bucket.',
    },
    'c': {
      true: '1. The group consists of Physics, Chemistry and Biology.\n2. The duration of the examination will be 150 minutes.\n3. You need to attempt all the 198 Multi-Choice Questions.\n4. The mock examination consists of 50 questions each from Physics and Chemistry, 98 questions from Biology.\n5. All the questions in level-3 mock examination will appear 40% from medium and 60% from complex category questions bank.\n6. You need to score 70% and more marks in each of the 50 consecutive examinations to qualify for the next level.\n7. In case, you want to leave the examination due to some unavoidable situation, the same examination will continue for the remaining time. You will not be able to attempt the next examination.\n8. All your attempted examinations will be saved in the Evaluation bucket to enable to monitor your average score.\n9. You will also be able to evaluate each and every attempted examination question by question in the Evaluation bucket.',
      false: '1. The group consists of Physics, Chemistry and Mathematics.\n2. The duration of the examination will be 150 minutes.\n3. You need to attempt all the 198 Multi-Choice Questions.\n4. The mock examination consists of 50 questions each from Physics and Chemistry, 98 questions from Mathematics.\n5. All the questions in level-3 mock examination will appear 40% from medium and 60% from complex category questions bank.\n6. You need to score 70% and more marks in each of the 50 consecutive examinations to qualify for the next level.\n7. In case, you want to leave the examination due to some unavoidable situation, the same examination will continue for the remaining time. You will not be able to attempt the next examination.\n8. All your attempted examinations will be saved in the Evaluation bucket to enable to monitor your average score.\n9. You will also be able to evaluate each and every attempted examination question by question in the Evaluation bucket.',
    },
    'd': {
      true: '1. The group consists of Physics, Chemistry and Biology.\n2. The duration of the examination will be 150 minutes.\n3. You need to attempt all the 198 Multi-Choice Questions.\n4. The mock examination consists of 50 questions each from Physics and Chemistry, 98 questions from Biology.\n5. All the questions in level-4 mock examination will appear 50% from complex and 50% from difficult category questions bank.\n6. You need to score 70% and more marks in each of the 50 consecutive examinations to qualify for the next level.\n7. In case, you want to leave the examination due to some unavoidable situation, the same examination will continue for the remaining time. You will not be able to attempt the next examination.\n8. All your attempted examinations will be saved in the Evaluation bucket to enable to monitor your average score.\n9. You will also be able to evaluate each and every attempted examination question by question in the Evaluation bucket.',
      false: '1. The group consists of Physics, Chemistry and Mathematics.\n2. The duration of the examination will be 150 minutes.\n3. You need to attempt all the 198 Multi-Choice Questions.\n4. The mock examination consists of 50 questions each from Physics and Chemistry, 98 questions from Mathematics.\n5. All the questions in level-4 mock examination will appear 50% from complex and 50% from difficult category questions bank.\n6. You need to score 70% and more marks in each of the 50 consecutive examinations to qualify for the next level.\n7. In case, you want to leave the examination due to some unavoidable situation, the same examination will continue for the remaining time. You will not be able to attempt the next examination.\n8. All your attempted examinations will be saved in the Evaluation bucket to enable to monitor your average score.\n9. You will also be able to evaluate each and every attempted examination question by question in the Evaluation bucket.',
    },
    'a': {
      true: '1. The group consists of Physics, Chemistry and Biology.\n2. The duration of the examination will be 150 minutes.\n3. You need to attempt all the 198 Multi-Choice Questions.\n4. The mock examination consists of 50 questions each from Physics and Chemistry, 98 questions from Biology.\n5. All the questions in level-5 mock examination will appear 30% from complex, 30% from difficult and 40% from advanced category questions bank.\n6. You need to score 70% and more marks in each of the 50 consecutive examinations to qualify for the next level.\n7. In case, you want to leave the examination due to some unavoidable situation, the same examination will continue for the remaining time. You will not be able to attempt the next examination.\n8. All your attempted examinations will be saved in the Evaluation bucket to enable to monitor your average score.\n9. You will also be able to evaluate each and every attempted examination question by question in the Evaluation bucket.',
      false: '1. The group consists of Physics, Chemistry and Mathematics.\n2. The duration of the examination will be 150 minutes.\n3. You need to attempt all the 198 Multi-Choice Questions.\n4. The mock examination consists of 50 questions each from Physics and Chemistry, 98 questions from Mathematics.\n5. All the questions in level-5 mock examination will appear 30% from complex, 30% from difficult and 40% from advanced category questions bank.\n6. You need to score 70% and more marks in each of the 50 consecutive examinations to qualify for the next level.\n7. In case, you want to leave the examination due to some unavoidable situation, the same examination will continue for the remaining time. You will not be able to attempt the next examination.\n8. All your attempted examinations will be saved in the Evaluation bucket to enable to monitor your average score.\n9. You will also be able to evaluate each and every attempted examination question by question in the Evaluation bucket.',
    }
  };
}